# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 MASH project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

# If docker userns is activated, the files that are mounted in the container must have a different uid and gid on the Docker host.
- name: Determine uid and gid for the directories which are mounted in the container
  ansible.builtin.set_fact:
    ntfy_host_filesystem_uid: "{{ ntfy_uid if not ntfy_docker_userns_enabled else (ntfy_uid | int + ntfy_docker_userns_offset) | string }}"
    ntfy_host_filesystem_gid: "{{ ntfy_gid if not ntfy_docker_userns_enabled else (ntfy_gid | int + ntfy_docker_userns_offset) | string }}"
  when: ntfy_enabled | bool
  tags:
    - always

- name: Perform ntfy installation tasks
  when: ntfy_enabled | bool
  tags:
    - setup-all
    - setup-ntfy
    - install-all
    - install-ntfy
  block:
    - name: Validate ntfy configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install ntfy
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
    - name: Set up ntfy users
      when:
        - ntfy_credentials | length > 0
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_users.yml"

- name: Perform ntfy uninstallation tasks
  when: not ntfy_enabled | bool
  tags:
    - setup-all
    - setup-ntfy
  block:
    - name: Uninstall ntfy
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"

- name: Perform ntfy self-check tasks
  when: ntfy_enabled | bool
  tags:
    - self-check
  block:
    - name: Run self-check for ntfy
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check.yml"
