# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of ntfy systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ ntfy_identifier }}.service"
  register: ntfy_service_stat

- name: Uninstall ntfy systemd services and files
  when: ntfy_service_stat.stat.exists | bool
  block:
    - name: Ensure ntfy systemd service is stopped
      ansible.builtin.service:
        name: "{{ ntfy_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure ntfy systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ ntfy_identifier }}.service"
        state: absent

    - name: Ensure ntfy path does not exist
      ansible.builtin.file:
        path: "{{ ntfy_base_path }}"
        state: absent
